//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.7.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from SRZ.g4 by ANTLR 4.7.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace Roslesinforg.Sigma.SrzParser {
using System;
using System.IO;
using System.Text;
using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;
using DFA = Antlr4.Runtime.Dfa.DFA;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.7.2")]
[System.CLSCompliant(false)]
public partial class SRZLexer : Lexer {
	protected static DFA[] decisionToDFA;
	protected static PredictionContextCache sharedContextCache = new PredictionContextCache();
	public const int
		DOT=1, COMMA=2, OPENBR=3, CLOSEBR=4, MUL=5, DIV=6, ADD=7, SUB=8, UNDERSCORE=9, 
		ID=10, INT=11, NUMBER=12, EQU=13, NOTEQU=14, AND=15, OR=16, LT=17, GT=18, 
		LE=19, GE=20, WHITESPACE=21, COMMENT=22, NEWLINE=23, STRING=24;
	public static string[] channelNames = {
		"DEFAULT_TOKEN_CHANNEL", "HIDDEN"
	};

	public static string[] modeNames = {
		"DEFAULT_MODE"
	};

	public static readonly string[] ruleNames = {
		"DOT", "COMMA", "OPENBR", "CLOSEBR", "MUL", "DIV", "ADD", "SUB", "LETTER", 
		"DIGIT", "UNDERSCORE", "ID", "INT", "NUMBER", "EQU", "NOTEQU", "AND", 
		"OR", "LT", "GT", "LE", "GE", "WHITESPACE", "COMMENT", "NEWLINE", "STRING", 
		"ESC", "UNICODE", "HEX"
	};


	public SRZLexer(ICharStream input)
	: this(input, Console.Out, Console.Error) { }

	public SRZLexer(ICharStream input, TextWriter output, TextWriter errorOutput)
	: base(input, output, errorOutput)
	{
		Interpreter = new LexerATNSimulator(this, _ATN, decisionToDFA, sharedContextCache);
	}

	private static readonly string[] _LiteralNames = {
		null, "'.'", "','", "'('", "')'", "'*'", "'/'", "'+'", "'-'", "'_'", null, 
		null, null, "'='", null, null, null, "'<'", "'>'"
	};
	private static readonly string[] _SymbolicNames = {
		null, "DOT", "COMMA", "OPENBR", "CLOSEBR", "MUL", "DIV", "ADD", "SUB", 
		"UNDERSCORE", "ID", "INT", "NUMBER", "EQU", "NOTEQU", "AND", "OR", "LT", 
		"GT", "LE", "GE", "WHITESPACE", "COMMENT", "NEWLINE", "STRING"
	};
	public static readonly IVocabulary DefaultVocabulary = new Vocabulary(_LiteralNames, _SymbolicNames);

	[NotNull]
	public override IVocabulary Vocabulary
	{
		get
		{
			return DefaultVocabulary;
		}
	}

	public override string GrammarFileName { get { return "SRZ.g4"; } }

	public override string[] RuleNames { get { return ruleNames; } }

	public override string[] ChannelNames { get { return channelNames; } }

	public override string[] ModeNames { get { return modeNames; } }

	public override string SerializedAtn { get { return new string(_serializedATN); } }

	static SRZLexer() {
		decisionToDFA = new DFA[_ATN.NumberOfDecisions];
		for (int i = 0; i < _ATN.NumberOfDecisions; i++) {
			decisionToDFA[i] = new DFA(_ATN.GetDecisionState(i), i);
		}
	}
	private static char[] _serializedATN = {
		'\x3', '\x608B', '\xA72A', '\x8133', '\xB9ED', '\x417C', '\x3BE7', '\x7786', 
		'\x5964', '\x2', '\x1A', '\xBC', '\b', '\x1', '\x4', '\x2', '\t', '\x2', 
		'\x4', '\x3', '\t', '\x3', '\x4', '\x4', '\t', '\x4', '\x4', '\x5', '\t', 
		'\x5', '\x4', '\x6', '\t', '\x6', '\x4', '\a', '\t', '\a', '\x4', '\b', 
		'\t', '\b', '\x4', '\t', '\t', '\t', '\x4', '\n', '\t', '\n', '\x4', '\v', 
		'\t', '\v', '\x4', '\f', '\t', '\f', '\x4', '\r', '\t', '\r', '\x4', '\xE', 
		'\t', '\xE', '\x4', '\xF', '\t', '\xF', '\x4', '\x10', '\t', '\x10', '\x4', 
		'\x11', '\t', '\x11', '\x4', '\x12', '\t', '\x12', '\x4', '\x13', '\t', 
		'\x13', '\x4', '\x14', '\t', '\x14', '\x4', '\x15', '\t', '\x15', '\x4', 
		'\x16', '\t', '\x16', '\x4', '\x17', '\t', '\x17', '\x4', '\x18', '\t', 
		'\x18', '\x4', '\x19', '\t', '\x19', '\x4', '\x1A', '\t', '\x1A', '\x4', 
		'\x1B', '\t', '\x1B', '\x4', '\x1C', '\t', '\x1C', '\x4', '\x1D', '\t', 
		'\x1D', '\x4', '\x1E', '\t', '\x1E', '\x3', '\x2', '\x3', '\x2', '\x3', 
		'\x3', '\x3', '\x3', '\x3', '\x4', '\x3', '\x4', '\x3', '\x5', '\x3', 
		'\x5', '\x3', '\x6', '\x3', '\x6', '\x3', '\a', '\x3', '\a', '\x3', '\b', 
		'\x3', '\b', '\x3', '\t', '\x3', '\t', '\x3', '\n', '\x3', '\n', '\x3', 
		'\v', '\x3', '\v', '\x3', '\f', '\x3', '\f', '\x3', '\r', '\x3', '\r', 
		'\a', '\r', 'V', '\n', '\r', '\f', '\r', '\xE', '\r', 'Y', '\v', '\r', 
		'\x3', '\xE', '\x6', '\xE', '\\', '\n', '\xE', '\r', '\xE', '\xE', '\xE', 
		']', '\x3', '\xF', '\x6', '\xF', '\x61', '\n', '\xF', '\r', '\xF', '\xE', 
		'\xF', '\x62', '\x3', '\xF', '\x3', '\xF', '\x6', '\xF', 'g', '\n', '\xF', 
		'\r', '\xF', '\xE', '\xF', 'h', '\x5', '\xF', 'k', '\n', '\xF', '\x3', 
		'\x10', '\x3', '\x10', '\x3', '\x11', '\x3', '\x11', '\x3', '\x11', '\x3', 
		'\x11', '\x3', '\x11', '\x5', '\x11', 't', '\n', '\x11', '\x3', '\x12', 
		'\x3', '\x12', '\x3', '\x12', '\x3', '\x12', '\x5', '\x12', 'z', '\n', 
		'\x12', '\x3', '\x13', '\x3', '\x13', '\x3', '\x13', '\x5', '\x13', '\x7F', 
		'\n', '\x13', '\x3', '\x14', '\x3', '\x14', '\x3', '\x15', '\x3', '\x15', 
		'\x3', '\x16', '\x3', '\x16', '\x3', '\x16', '\x3', '\x17', '\x3', '\x17', 
		'\x3', '\x17', '\x3', '\x18', '\x6', '\x18', '\x8C', '\n', '\x18', '\r', 
		'\x18', '\xE', '\x18', '\x8D', '\x3', '\x18', '\x3', '\x18', '\x3', '\x19', 
		'\x3', '\x19', '\a', '\x19', '\x94', '\n', '\x19', '\f', '\x19', '\xE', 
		'\x19', '\x97', '\v', '\x19', '\x3', '\x19', '\x3', '\x19', '\x3', '\x1A', 
		'\x5', '\x1A', '\x9C', '\n', '\x1A', '\x3', '\x1A', '\x3', '\x1A', '\x6', 
		'\x1A', '\xA0', '\n', '\x1A', '\r', '\x1A', '\xE', '\x1A', '\xA1', '\x3', 
		'\x1A', '\x3', '\x1A', '\x3', '\x1B', '\x3', '\x1B', '\x3', '\x1B', '\a', 
		'\x1B', '\xA9', '\n', '\x1B', '\f', '\x1B', '\xE', '\x1B', '\xAC', '\v', 
		'\x1B', '\x3', '\x1B', '\x3', '\x1B', '\x3', '\x1C', '\x3', '\x1C', '\x3', 
		'\x1C', '\x5', '\x1C', '\xB3', '\n', '\x1C', '\x3', '\x1D', '\x3', '\x1D', 
		'\x3', '\x1D', '\x3', '\x1D', '\x3', '\x1D', '\x3', '\x1D', '\x3', '\x1E', 
		'\x3', '\x1E', '\x2', '\x2', '\x1F', '\x3', '\x3', '\x5', '\x4', '\a', 
		'\x5', '\t', '\x6', '\v', '\a', '\r', '\b', '\xF', '\t', '\x11', '\n', 
		'\x13', '\x2', '\x15', '\x2', '\x17', '\v', '\x19', '\f', '\x1B', '\r', 
		'\x1D', '\xE', '\x1F', '\xF', '!', '\x10', '#', '\x11', '%', '\x12', '\'', 
		'\x13', ')', '\x14', '+', '\x15', '-', '\x16', '/', '\x17', '\x31', '\x18', 
		'\x33', '\x19', '\x35', '\x1A', '\x37', '\x2', '\x39', '\x2', ';', '\x2', 
		'\x3', '\x2', '\f', '\x4', '\x2', '\x43', '\\', '\x63', '|', '\x3', '\x2', 
		'\x32', ';', '\x5', '\x2', '\x43', '\\', '\x61', '\x61', '\x63', '|', 
		'\x6', '\x2', '\x32', ';', '\x43', '\\', '\x61', '\x61', '\x63', '|', 
		'\x4', '\x2', '#', '#', '~', '~', '\x4', '\x2', '\v', '\v', '\"', '\"', 
		'\x4', '\x2', '\f', '\f', '\xF', '\xF', '\x4', '\x2', '$', '$', '^', '^', 
		'\n', '\x2', '$', '$', '\x31', '\x31', '^', '^', '\x64', '\x64', 'h', 
		'h', 'p', 'p', 't', 't', 'v', 'v', '\x5', '\x2', '\x32', ';', '\x43', 
		'H', '\x63', 'h', '\x2', '\xC7', '\x2', '\x3', '\x3', '\x2', '\x2', '\x2', 
		'\x2', '\x5', '\x3', '\x2', '\x2', '\x2', '\x2', '\a', '\x3', '\x2', '\x2', 
		'\x2', '\x2', '\t', '\x3', '\x2', '\x2', '\x2', '\x2', '\v', '\x3', '\x2', 
		'\x2', '\x2', '\x2', '\r', '\x3', '\x2', '\x2', '\x2', '\x2', '\xF', '\x3', 
		'\x2', '\x2', '\x2', '\x2', '\x11', '\x3', '\x2', '\x2', '\x2', '\x2', 
		'\x17', '\x3', '\x2', '\x2', '\x2', '\x2', '\x19', '\x3', '\x2', '\x2', 
		'\x2', '\x2', '\x1B', '\x3', '\x2', '\x2', '\x2', '\x2', '\x1D', '\x3', 
		'\x2', '\x2', '\x2', '\x2', '\x1F', '\x3', '\x2', '\x2', '\x2', '\x2', 
		'!', '\x3', '\x2', '\x2', '\x2', '\x2', '#', '\x3', '\x2', '\x2', '\x2', 
		'\x2', '%', '\x3', '\x2', '\x2', '\x2', '\x2', '\'', '\x3', '\x2', '\x2', 
		'\x2', '\x2', ')', '\x3', '\x2', '\x2', '\x2', '\x2', '+', '\x3', '\x2', 
		'\x2', '\x2', '\x2', '-', '\x3', '\x2', '\x2', '\x2', '\x2', '/', '\x3', 
		'\x2', '\x2', '\x2', '\x2', '\x31', '\x3', '\x2', '\x2', '\x2', '\x2', 
		'\x33', '\x3', '\x2', '\x2', '\x2', '\x2', '\x35', '\x3', '\x2', '\x2', 
		'\x2', '\x3', '=', '\x3', '\x2', '\x2', '\x2', '\x5', '?', '\x3', '\x2', 
		'\x2', '\x2', '\a', '\x41', '\x3', '\x2', '\x2', '\x2', '\t', '\x43', 
		'\x3', '\x2', '\x2', '\x2', '\v', '\x45', '\x3', '\x2', '\x2', '\x2', 
		'\r', 'G', '\x3', '\x2', '\x2', '\x2', '\xF', 'I', '\x3', '\x2', '\x2', 
		'\x2', '\x11', 'K', '\x3', '\x2', '\x2', '\x2', '\x13', 'M', '\x3', '\x2', 
		'\x2', '\x2', '\x15', 'O', '\x3', '\x2', '\x2', '\x2', '\x17', 'Q', '\x3', 
		'\x2', '\x2', '\x2', '\x19', 'S', '\x3', '\x2', '\x2', '\x2', '\x1B', 
		'[', '\x3', '\x2', '\x2', '\x2', '\x1D', '`', '\x3', '\x2', '\x2', '\x2', 
		'\x1F', 'l', '\x3', '\x2', '\x2', '\x2', '!', 's', '\x3', '\x2', '\x2', 
		'\x2', '#', 'y', '\x3', '\x2', '\x2', '\x2', '%', '~', '\x3', '\x2', '\x2', 
		'\x2', '\'', '\x80', '\x3', '\x2', '\x2', '\x2', ')', '\x82', '\x3', '\x2', 
		'\x2', '\x2', '+', '\x84', '\x3', '\x2', '\x2', '\x2', '-', '\x87', '\x3', 
		'\x2', '\x2', '\x2', '/', '\x8B', '\x3', '\x2', '\x2', '\x2', '\x31', 
		'\x91', '\x3', '\x2', '\x2', '\x2', '\x33', '\x9F', '\x3', '\x2', '\x2', 
		'\x2', '\x35', '\xA5', '\x3', '\x2', '\x2', '\x2', '\x37', '\xAF', '\x3', 
		'\x2', '\x2', '\x2', '\x39', '\xB4', '\x3', '\x2', '\x2', '\x2', ';', 
		'\xBA', '\x3', '\x2', '\x2', '\x2', '=', '>', '\a', '\x30', '\x2', '\x2', 
		'>', '\x4', '\x3', '\x2', '\x2', '\x2', '?', '@', '\a', '.', '\x2', '\x2', 
		'@', '\x6', '\x3', '\x2', '\x2', '\x2', '\x41', '\x42', '\a', '*', '\x2', 
		'\x2', '\x42', '\b', '\x3', '\x2', '\x2', '\x2', '\x43', '\x44', '\a', 
		'+', '\x2', '\x2', '\x44', '\n', '\x3', '\x2', '\x2', '\x2', '\x45', '\x46', 
		'\a', ',', '\x2', '\x2', '\x46', '\f', '\x3', '\x2', '\x2', '\x2', 'G', 
		'H', '\a', '\x31', '\x2', '\x2', 'H', '\xE', '\x3', '\x2', '\x2', '\x2', 
		'I', 'J', '\a', '-', '\x2', '\x2', 'J', '\x10', '\x3', '\x2', '\x2', '\x2', 
		'K', 'L', '\a', '/', '\x2', '\x2', 'L', '\x12', '\x3', '\x2', '\x2', '\x2', 
		'M', 'N', '\t', '\x2', '\x2', '\x2', 'N', '\x14', '\x3', '\x2', '\x2', 
		'\x2', 'O', 'P', '\t', '\x3', '\x2', '\x2', 'P', '\x16', '\x3', '\x2', 
		'\x2', '\x2', 'Q', 'R', '\a', '\x61', '\x2', '\x2', 'R', '\x18', '\x3', 
		'\x2', '\x2', '\x2', 'S', 'W', '\t', '\x4', '\x2', '\x2', 'T', 'V', '\t', 
		'\x5', '\x2', '\x2', 'U', 'T', '\x3', '\x2', '\x2', '\x2', 'V', 'Y', '\x3', 
		'\x2', '\x2', '\x2', 'W', 'U', '\x3', '\x2', '\x2', '\x2', 'W', 'X', '\x3', 
		'\x2', '\x2', '\x2', 'X', '\x1A', '\x3', '\x2', '\x2', '\x2', 'Y', 'W', 
		'\x3', '\x2', '\x2', '\x2', 'Z', '\\', '\x5', '\x15', '\v', '\x2', '[', 
		'Z', '\x3', '\x2', '\x2', '\x2', '\\', ']', '\x3', '\x2', '\x2', '\x2', 
		']', '[', '\x3', '\x2', '\x2', '\x2', ']', '^', '\x3', '\x2', '\x2', '\x2', 
		'^', '\x1C', '\x3', '\x2', '\x2', '\x2', '_', '\x61', '\x5', '\x15', '\v', 
		'\x2', '`', '_', '\x3', '\x2', '\x2', '\x2', '\x61', '\x62', '\x3', '\x2', 
		'\x2', '\x2', '\x62', '`', '\x3', '\x2', '\x2', '\x2', '\x62', '\x63', 
		'\x3', '\x2', '\x2', '\x2', '\x63', 'j', '\x3', '\x2', '\x2', '\x2', '\x64', 
		'\x66', '\x5', '\x3', '\x2', '\x2', '\x65', 'g', '\x5', '\x15', '\v', 
		'\x2', '\x66', '\x65', '\x3', '\x2', '\x2', '\x2', 'g', 'h', '\x3', '\x2', 
		'\x2', '\x2', 'h', '\x66', '\x3', '\x2', '\x2', '\x2', 'h', 'i', '\x3', 
		'\x2', '\x2', '\x2', 'i', 'k', '\x3', '\x2', '\x2', '\x2', 'j', '\x64', 
		'\x3', '\x2', '\x2', '\x2', 'j', 'k', '\x3', '\x2', '\x2', '\x2', 'k', 
		'\x1E', '\x3', '\x2', '\x2', '\x2', 'l', 'm', '\a', '?', '\x2', '\x2', 
		'm', ' ', '\x3', '\x2', '\x2', '\x2', 'n', 'o', '\a', '#', '\x2', '\x2', 
		'o', 't', '\a', '?', '\x2', '\x2', 'p', 'q', '\a', '>', '\x2', '\x2', 
		'q', 't', '\a', '@', '\x2', '\x2', 'r', 't', '\a', '%', '\x2', '\x2', 
		's', 'n', '\x3', '\x2', '\x2', '\x2', 's', 'p', '\x3', '\x2', '\x2', '\x2', 
		's', 'r', '\x3', '\x2', '\x2', '\x2', 't', '\"', '\x3', '\x2', '\x2', 
		'\x2', 'u', 'z', '\a', '(', '\x2', '\x2', 'v', 'w', '\a', '\x43', '\x2', 
		'\x2', 'w', 'x', '\a', 'P', '\x2', '\x2', 'x', 'z', '\a', '\x46', '\x2', 
		'\x2', 'y', 'u', '\x3', '\x2', '\x2', '\x2', 'y', 'v', '\x3', '\x2', '\x2', 
		'\x2', 'z', '$', '\x3', '\x2', '\x2', '\x2', '{', '\x7F', '\t', '\x6', 
		'\x2', '\x2', '|', '}', '\a', 'Q', '\x2', '\x2', '}', '\x7F', '\a', 'T', 
		'\x2', '\x2', '~', '{', '\x3', '\x2', '\x2', '\x2', '~', '|', '\x3', '\x2', 
		'\x2', '\x2', '\x7F', '&', '\x3', '\x2', '\x2', '\x2', '\x80', '\x81', 
		'\a', '>', '\x2', '\x2', '\x81', '(', '\x3', '\x2', '\x2', '\x2', '\x82', 
		'\x83', '\a', '@', '\x2', '\x2', '\x83', '*', '\x3', '\x2', '\x2', '\x2', 
		'\x84', '\x85', '\x5', '\'', '\x14', '\x2', '\x85', '\x86', '\x5', '\x1F', 
		'\x10', '\x2', '\x86', ',', '\x3', '\x2', '\x2', '\x2', '\x87', '\x88', 
		'\x5', ')', '\x15', '\x2', '\x88', '\x89', '\x5', '\x1F', '\x10', '\x2', 
		'\x89', '.', '\x3', '\x2', '\x2', '\x2', '\x8A', '\x8C', '\t', '\a', '\x2', 
		'\x2', '\x8B', '\x8A', '\x3', '\x2', '\x2', '\x2', '\x8C', '\x8D', '\x3', 
		'\x2', '\x2', '\x2', '\x8D', '\x8B', '\x3', '\x2', '\x2', '\x2', '\x8D', 
		'\x8E', '\x3', '\x2', '\x2', '\x2', '\x8E', '\x8F', '\x3', '\x2', '\x2', 
		'\x2', '\x8F', '\x90', '\b', '\x18', '\x2', '\x2', '\x90', '\x30', '\x3', 
		'\x2', '\x2', '\x2', '\x91', '\x95', '\a', '=', '\x2', '\x2', '\x92', 
		'\x94', '\n', '\b', '\x2', '\x2', '\x93', '\x92', '\x3', '\x2', '\x2', 
		'\x2', '\x94', '\x97', '\x3', '\x2', '\x2', '\x2', '\x95', '\x93', '\x3', 
		'\x2', '\x2', '\x2', '\x95', '\x96', '\x3', '\x2', '\x2', '\x2', '\x96', 
		'\x98', '\x3', '\x2', '\x2', '\x2', '\x97', '\x95', '\x3', '\x2', '\x2', 
		'\x2', '\x98', '\x99', '\b', '\x19', '\x3', '\x2', '\x99', '\x32', '\x3', 
		'\x2', '\x2', '\x2', '\x9A', '\x9C', '\a', '\xF', '\x2', '\x2', '\x9B', 
		'\x9A', '\x3', '\x2', '\x2', '\x2', '\x9B', '\x9C', '\x3', '\x2', '\x2', 
		'\x2', '\x9C', '\x9D', '\x3', '\x2', '\x2', '\x2', '\x9D', '\xA0', '\a', 
		'\f', '\x2', '\x2', '\x9E', '\xA0', '\a', '\xF', '\x2', '\x2', '\x9F', 
		'\x9B', '\x3', '\x2', '\x2', '\x2', '\x9F', '\x9E', '\x3', '\x2', '\x2', 
		'\x2', '\xA0', '\xA1', '\x3', '\x2', '\x2', '\x2', '\xA1', '\x9F', '\x3', 
		'\x2', '\x2', '\x2', '\xA1', '\xA2', '\x3', '\x2', '\x2', '\x2', '\xA2', 
		'\xA3', '\x3', '\x2', '\x2', '\x2', '\xA3', '\xA4', '\b', '\x1A', '\x2', 
		'\x2', '\xA4', '\x34', '\x3', '\x2', '\x2', '\x2', '\xA5', '\xAA', '\a', 
		'$', '\x2', '\x2', '\xA6', '\xA9', '\x5', '\x37', '\x1C', '\x2', '\xA7', 
		'\xA9', '\n', '\t', '\x2', '\x2', '\xA8', '\xA6', '\x3', '\x2', '\x2', 
		'\x2', '\xA8', '\xA7', '\x3', '\x2', '\x2', '\x2', '\xA9', '\xAC', '\x3', 
		'\x2', '\x2', '\x2', '\xAA', '\xA8', '\x3', '\x2', '\x2', '\x2', '\xAA', 
		'\xAB', '\x3', '\x2', '\x2', '\x2', '\xAB', '\xAD', '\x3', '\x2', '\x2', 
		'\x2', '\xAC', '\xAA', '\x3', '\x2', '\x2', '\x2', '\xAD', '\xAE', '\a', 
		'$', '\x2', '\x2', '\xAE', '\x36', '\x3', '\x2', '\x2', '\x2', '\xAF', 
		'\xB2', '\a', '^', '\x2', '\x2', '\xB0', '\xB3', '\t', '\n', '\x2', '\x2', 
		'\xB1', '\xB3', '\x5', '\x39', '\x1D', '\x2', '\xB2', '\xB0', '\x3', '\x2', 
		'\x2', '\x2', '\xB2', '\xB1', '\x3', '\x2', '\x2', '\x2', '\xB3', '\x38', 
		'\x3', '\x2', '\x2', '\x2', '\xB4', '\xB5', '\a', 'w', '\x2', '\x2', '\xB5', 
		'\xB6', '\x5', ';', '\x1E', '\x2', '\xB6', '\xB7', '\x5', ';', '\x1E', 
		'\x2', '\xB7', '\xB8', '\x5', ';', '\x1E', '\x2', '\xB8', '\xB9', '\x5', 
		';', '\x1E', '\x2', '\xB9', ':', '\x3', '\x2', '\x2', '\x2', '\xBA', '\xBB', 
		'\t', '\v', '\x2', '\x2', '\xBB', '<', '\x3', '\x2', '\x2', '\x2', '\x13', 
		'\x2', 'W', ']', '\x62', 'h', 'j', 's', 'y', '~', '\x8D', '\x95', '\x9B', 
		'\x9F', '\xA1', '\xA8', '\xAA', '\xB2', '\x4', '\b', '\x2', '\x2', '\x2', 
		'\x3', '\x2',
	};

	public static readonly ATN _ATN =
		new ATNDeserializer().Deserialize(_serializedATN);


}
} // namespace Roslesinforg.Sigma.SrzParser
