//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.7.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from SRZ.g4 by ANTLR 4.7.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace Roslesinforg.Sigma.SrzParser {
using System;
using System.IO;
using System.Text;
using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;
using DFA = Antlr4.Runtime.Dfa.DFA;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.7.2")]
[System.CLSCompliant(false)]
public partial class SRZLexer : Lexer {
	protected static DFA[] decisionToDFA;
	protected static PredictionContextCache sharedContextCache = new PredictionContextCache();
	public const int
		T__0=1, DOT=2, COMMA=3, OPENBR=4, CLOSEBR=5, MUL=6, DIV=7, ADD=8, SUB=9, 
		UNDERSCORE=10, ID=11, INT=12, NUMBER=13, EQU=14, NOTEQU=15, AND=16, OR=17, 
		LT=18, GT=19, LE=20, GE=21, WHITESPACE=22, COMMENT=23, NEWLINE=24, STRING=25;
	public static string[] channelNames = {
		"DEFAULT_TOKEN_CHANNEL", "HIDDEN"
	};

	public static string[] modeNames = {
		"DEFAULT_MODE"
	};

	public static readonly string[] ruleNames = {
		"T__0", "DOT", "COMMA", "OPENBR", "CLOSEBR", "MUL", "DIV", "ADD", "SUB", 
		"LETTER", "DIGIT", "UNDERSCORE", "ID", "INT", "NUMBER", "EQU", "NOTEQU", 
		"AND", "OR", "LT", "GT", "LE", "GE", "WHITESPACE", "COMMENT", "NEWLINE", 
		"STRING", "ESC", "UNICODE", "HEX"
	};


	public SRZLexer(ICharStream input)
	: this(input, Console.Out, Console.Error) { }

	public SRZLexer(ICharStream input, TextWriter output, TextWriter errorOutput)
	: base(input, output, errorOutput)
	{
		Interpreter = new LexerATNSimulator(this, _ATN, decisionToDFA, sharedContextCache);
	}

	private static readonly string[] _LiteralNames = {
		null, "'Any'", "'.'", "','", "'('", "')'", "'*'", "'/'", "'+'", "'-'", 
		"'_'", null, null, null, "'='", null, null, null, "'<'", "'>'"
	};
	private static readonly string[] _SymbolicNames = {
		null, null, "DOT", "COMMA", "OPENBR", "CLOSEBR", "MUL", "DIV", "ADD", 
		"SUB", "UNDERSCORE", "ID", "INT", "NUMBER", "EQU", "NOTEQU", "AND", "OR", 
		"LT", "GT", "LE", "GE", "WHITESPACE", "COMMENT", "NEWLINE", "STRING"
	};
	public static readonly IVocabulary DefaultVocabulary = new Vocabulary(_LiteralNames, _SymbolicNames);

	[NotNull]
	public override IVocabulary Vocabulary
	{
		get
		{
			return DefaultVocabulary;
		}
	}

	public override string GrammarFileName { get { return "SRZ.g4"; } }

	public override string[] RuleNames { get { return ruleNames; } }

	public override string[] ChannelNames { get { return channelNames; } }

	public override string[] ModeNames { get { return modeNames; } }

	public override string SerializedAtn { get { return new string(_serializedATN); } }

	static SRZLexer() {
		decisionToDFA = new DFA[_ATN.NumberOfDecisions];
		for (int i = 0; i < _ATN.NumberOfDecisions; i++) {
			decisionToDFA[i] = new DFA(_ATN.GetDecisionState(i), i);
		}
	}
	private static char[] _serializedATN = {
		'\x3', '\x608B', '\xA72A', '\x8133', '\xB9ED', '\x417C', '\x3BE7', '\x7786', 
		'\x5964', '\x2', '\x1B', '\xC2', '\b', '\x1', '\x4', '\x2', '\t', '\x2', 
		'\x4', '\x3', '\t', '\x3', '\x4', '\x4', '\t', '\x4', '\x4', '\x5', '\t', 
		'\x5', '\x4', '\x6', '\t', '\x6', '\x4', '\a', '\t', '\a', '\x4', '\b', 
		'\t', '\b', '\x4', '\t', '\t', '\t', '\x4', '\n', '\t', '\n', '\x4', '\v', 
		'\t', '\v', '\x4', '\f', '\t', '\f', '\x4', '\r', '\t', '\r', '\x4', '\xE', 
		'\t', '\xE', '\x4', '\xF', '\t', '\xF', '\x4', '\x10', '\t', '\x10', '\x4', 
		'\x11', '\t', '\x11', '\x4', '\x12', '\t', '\x12', '\x4', '\x13', '\t', 
		'\x13', '\x4', '\x14', '\t', '\x14', '\x4', '\x15', '\t', '\x15', '\x4', 
		'\x16', '\t', '\x16', '\x4', '\x17', '\t', '\x17', '\x4', '\x18', '\t', 
		'\x18', '\x4', '\x19', '\t', '\x19', '\x4', '\x1A', '\t', '\x1A', '\x4', 
		'\x1B', '\t', '\x1B', '\x4', '\x1C', '\t', '\x1C', '\x4', '\x1D', '\t', 
		'\x1D', '\x4', '\x1E', '\t', '\x1E', '\x4', '\x1F', '\t', '\x1F', '\x3', 
		'\x2', '\x3', '\x2', '\x3', '\x2', '\x3', '\x2', '\x3', '\x3', '\x3', 
		'\x3', '\x3', '\x4', '\x3', '\x4', '\x3', '\x5', '\x3', '\x5', '\x3', 
		'\x6', '\x3', '\x6', '\x3', '\a', '\x3', '\a', '\x3', '\b', '\x3', '\b', 
		'\x3', '\t', '\x3', '\t', '\x3', '\n', '\x3', '\n', '\x3', '\v', '\x3', 
		'\v', '\x3', '\f', '\x3', '\f', '\x3', '\r', '\x3', '\r', '\x3', '\xE', 
		'\x3', '\xE', '\a', '\xE', '\\', '\n', '\xE', '\f', '\xE', '\xE', '\xE', 
		'_', '\v', '\xE', '\x3', '\xF', '\x6', '\xF', '\x62', '\n', '\xF', '\r', 
		'\xF', '\xE', '\xF', '\x63', '\x3', '\x10', '\x6', '\x10', 'g', '\n', 
		'\x10', '\r', '\x10', '\xE', '\x10', 'h', '\x3', '\x10', '\x3', '\x10', 
		'\x6', '\x10', 'm', '\n', '\x10', '\r', '\x10', '\xE', '\x10', 'n', '\x5', 
		'\x10', 'q', '\n', '\x10', '\x3', '\x11', '\x3', '\x11', '\x3', '\x12', 
		'\x3', '\x12', '\x3', '\x12', '\x3', '\x12', '\x3', '\x12', '\x5', '\x12', 
		'z', '\n', '\x12', '\x3', '\x13', '\x3', '\x13', '\x3', '\x13', '\x3', 
		'\x13', '\x5', '\x13', '\x80', '\n', '\x13', '\x3', '\x14', '\x3', '\x14', 
		'\x3', '\x14', '\x5', '\x14', '\x85', '\n', '\x14', '\x3', '\x15', '\x3', 
		'\x15', '\x3', '\x16', '\x3', '\x16', '\x3', '\x17', '\x3', '\x17', '\x3', 
		'\x17', '\x3', '\x18', '\x3', '\x18', '\x3', '\x18', '\x3', '\x19', '\x6', 
		'\x19', '\x92', '\n', '\x19', '\r', '\x19', '\xE', '\x19', '\x93', '\x3', 
		'\x19', '\x3', '\x19', '\x3', '\x1A', '\x3', '\x1A', '\a', '\x1A', '\x9A', 
		'\n', '\x1A', '\f', '\x1A', '\xE', '\x1A', '\x9D', '\v', '\x1A', '\x3', 
		'\x1A', '\x3', '\x1A', '\x3', '\x1B', '\x5', '\x1B', '\xA2', '\n', '\x1B', 
		'\x3', '\x1B', '\x3', '\x1B', '\x6', '\x1B', '\xA6', '\n', '\x1B', '\r', 
		'\x1B', '\xE', '\x1B', '\xA7', '\x3', '\x1B', '\x3', '\x1B', '\x3', '\x1C', 
		'\x3', '\x1C', '\x3', '\x1C', '\a', '\x1C', '\xAF', '\n', '\x1C', '\f', 
		'\x1C', '\xE', '\x1C', '\xB2', '\v', '\x1C', '\x3', '\x1C', '\x3', '\x1C', 
		'\x3', '\x1D', '\x3', '\x1D', '\x3', '\x1D', '\x5', '\x1D', '\xB9', '\n', 
		'\x1D', '\x3', '\x1E', '\x3', '\x1E', '\x3', '\x1E', '\x3', '\x1E', '\x3', 
		'\x1E', '\x3', '\x1E', '\x3', '\x1F', '\x3', '\x1F', '\x2', '\x2', ' ', 
		'\x3', '\x3', '\x5', '\x4', '\a', '\x5', '\t', '\x6', '\v', '\a', '\r', 
		'\b', '\xF', '\t', '\x11', '\n', '\x13', '\v', '\x15', '\x2', '\x17', 
		'\x2', '\x19', '\f', '\x1B', '\r', '\x1D', '\xE', '\x1F', '\xF', '!', 
		'\x10', '#', '\x11', '%', '\x12', '\'', '\x13', ')', '\x14', '+', '\x15', 
		'-', '\x16', '/', '\x17', '\x31', '\x18', '\x33', '\x19', '\x35', '\x1A', 
		'\x37', '\x1B', '\x39', '\x2', ';', '\x2', '=', '\x2', '\x3', '\x2', '\f', 
		'\x4', '\x2', '\x43', '\\', '\x63', '|', '\x3', '\x2', '\x32', ';', '\x5', 
		'\x2', '\x43', '\\', '\x61', '\x61', '\x63', '|', '\x6', '\x2', '\x32', 
		';', '\x43', '\\', '\x61', '\x61', '\x63', '|', '\x4', '\x2', '#', '#', 
		'~', '~', '\x4', '\x2', '\v', '\v', '\"', '\"', '\x4', '\x2', '\f', '\f', 
		'\xF', '\xF', '\x4', '\x2', '$', '$', '^', '^', '\n', '\x2', '$', '$', 
		'\x31', '\x31', '^', '^', '\x64', '\x64', 'h', 'h', 'p', 'p', 't', 't', 
		'v', 'v', '\x5', '\x2', '\x32', ';', '\x43', 'H', '\x63', 'h', '\x2', 
		'\xCD', '\x2', '\x3', '\x3', '\x2', '\x2', '\x2', '\x2', '\x5', '\x3', 
		'\x2', '\x2', '\x2', '\x2', '\a', '\x3', '\x2', '\x2', '\x2', '\x2', '\t', 
		'\x3', '\x2', '\x2', '\x2', '\x2', '\v', '\x3', '\x2', '\x2', '\x2', '\x2', 
		'\r', '\x3', '\x2', '\x2', '\x2', '\x2', '\xF', '\x3', '\x2', '\x2', '\x2', 
		'\x2', '\x11', '\x3', '\x2', '\x2', '\x2', '\x2', '\x13', '\x3', '\x2', 
		'\x2', '\x2', '\x2', '\x19', '\x3', '\x2', '\x2', '\x2', '\x2', '\x1B', 
		'\x3', '\x2', '\x2', '\x2', '\x2', '\x1D', '\x3', '\x2', '\x2', '\x2', 
		'\x2', '\x1F', '\x3', '\x2', '\x2', '\x2', '\x2', '!', '\x3', '\x2', '\x2', 
		'\x2', '\x2', '#', '\x3', '\x2', '\x2', '\x2', '\x2', '%', '\x3', '\x2', 
		'\x2', '\x2', '\x2', '\'', '\x3', '\x2', '\x2', '\x2', '\x2', ')', '\x3', 
		'\x2', '\x2', '\x2', '\x2', '+', '\x3', '\x2', '\x2', '\x2', '\x2', '-', 
		'\x3', '\x2', '\x2', '\x2', '\x2', '/', '\x3', '\x2', '\x2', '\x2', '\x2', 
		'\x31', '\x3', '\x2', '\x2', '\x2', '\x2', '\x33', '\x3', '\x2', '\x2', 
		'\x2', '\x2', '\x35', '\x3', '\x2', '\x2', '\x2', '\x2', '\x37', '\x3', 
		'\x2', '\x2', '\x2', '\x3', '?', '\x3', '\x2', '\x2', '\x2', '\x5', '\x43', 
		'\x3', '\x2', '\x2', '\x2', '\a', '\x45', '\x3', '\x2', '\x2', '\x2', 
		'\t', 'G', '\x3', '\x2', '\x2', '\x2', '\v', 'I', '\x3', '\x2', '\x2', 
		'\x2', '\r', 'K', '\x3', '\x2', '\x2', '\x2', '\xF', 'M', '\x3', '\x2', 
		'\x2', '\x2', '\x11', 'O', '\x3', '\x2', '\x2', '\x2', '\x13', 'Q', '\x3', 
		'\x2', '\x2', '\x2', '\x15', 'S', '\x3', '\x2', '\x2', '\x2', '\x17', 
		'U', '\x3', '\x2', '\x2', '\x2', '\x19', 'W', '\x3', '\x2', '\x2', '\x2', 
		'\x1B', 'Y', '\x3', '\x2', '\x2', '\x2', '\x1D', '\x61', '\x3', '\x2', 
		'\x2', '\x2', '\x1F', '\x66', '\x3', '\x2', '\x2', '\x2', '!', 'r', '\x3', 
		'\x2', '\x2', '\x2', '#', 'y', '\x3', '\x2', '\x2', '\x2', '%', '\x7F', 
		'\x3', '\x2', '\x2', '\x2', '\'', '\x84', '\x3', '\x2', '\x2', '\x2', 
		')', '\x86', '\x3', '\x2', '\x2', '\x2', '+', '\x88', '\x3', '\x2', '\x2', 
		'\x2', '-', '\x8A', '\x3', '\x2', '\x2', '\x2', '/', '\x8D', '\x3', '\x2', 
		'\x2', '\x2', '\x31', '\x91', '\x3', '\x2', '\x2', '\x2', '\x33', '\x97', 
		'\x3', '\x2', '\x2', '\x2', '\x35', '\xA5', '\x3', '\x2', '\x2', '\x2', 
		'\x37', '\xAB', '\x3', '\x2', '\x2', '\x2', '\x39', '\xB5', '\x3', '\x2', 
		'\x2', '\x2', ';', '\xBA', '\x3', '\x2', '\x2', '\x2', '=', '\xC0', '\x3', 
		'\x2', '\x2', '\x2', '?', '@', '\a', '\x43', '\x2', '\x2', '@', '\x41', 
		'\a', 'p', '\x2', '\x2', '\x41', '\x42', '\a', '{', '\x2', '\x2', '\x42', 
		'\x4', '\x3', '\x2', '\x2', '\x2', '\x43', '\x44', '\a', '\x30', '\x2', 
		'\x2', '\x44', '\x6', '\x3', '\x2', '\x2', '\x2', '\x45', '\x46', '\a', 
		'.', '\x2', '\x2', '\x46', '\b', '\x3', '\x2', '\x2', '\x2', 'G', 'H', 
		'\a', '*', '\x2', '\x2', 'H', '\n', '\x3', '\x2', '\x2', '\x2', 'I', 'J', 
		'\a', '+', '\x2', '\x2', 'J', '\f', '\x3', '\x2', '\x2', '\x2', 'K', 'L', 
		'\a', ',', '\x2', '\x2', 'L', '\xE', '\x3', '\x2', '\x2', '\x2', 'M', 
		'N', '\a', '\x31', '\x2', '\x2', 'N', '\x10', '\x3', '\x2', '\x2', '\x2', 
		'O', 'P', '\a', '-', '\x2', '\x2', 'P', '\x12', '\x3', '\x2', '\x2', '\x2', 
		'Q', 'R', '\a', '/', '\x2', '\x2', 'R', '\x14', '\x3', '\x2', '\x2', '\x2', 
		'S', 'T', '\t', '\x2', '\x2', '\x2', 'T', '\x16', '\x3', '\x2', '\x2', 
		'\x2', 'U', 'V', '\t', '\x3', '\x2', '\x2', 'V', '\x18', '\x3', '\x2', 
		'\x2', '\x2', 'W', 'X', '\a', '\x61', '\x2', '\x2', 'X', '\x1A', '\x3', 
		'\x2', '\x2', '\x2', 'Y', ']', '\t', '\x4', '\x2', '\x2', 'Z', '\\', '\t', 
		'\x5', '\x2', '\x2', '[', 'Z', '\x3', '\x2', '\x2', '\x2', '\\', '_', 
		'\x3', '\x2', '\x2', '\x2', ']', '[', '\x3', '\x2', '\x2', '\x2', ']', 
		'^', '\x3', '\x2', '\x2', '\x2', '^', '\x1C', '\x3', '\x2', '\x2', '\x2', 
		'_', ']', '\x3', '\x2', '\x2', '\x2', '`', '\x62', '\x5', '\x17', '\f', 
		'\x2', '\x61', '`', '\x3', '\x2', '\x2', '\x2', '\x62', '\x63', '\x3', 
		'\x2', '\x2', '\x2', '\x63', '\x61', '\x3', '\x2', '\x2', '\x2', '\x63', 
		'\x64', '\x3', '\x2', '\x2', '\x2', '\x64', '\x1E', '\x3', '\x2', '\x2', 
		'\x2', '\x65', 'g', '\x5', '\x17', '\f', '\x2', '\x66', '\x65', '\x3', 
		'\x2', '\x2', '\x2', 'g', 'h', '\x3', '\x2', '\x2', '\x2', 'h', '\x66', 
		'\x3', '\x2', '\x2', '\x2', 'h', 'i', '\x3', '\x2', '\x2', '\x2', 'i', 
		'p', '\x3', '\x2', '\x2', '\x2', 'j', 'l', '\x5', '\x5', '\x3', '\x2', 
		'k', 'm', '\x5', '\x17', '\f', '\x2', 'l', 'k', '\x3', '\x2', '\x2', '\x2', 
		'm', 'n', '\x3', '\x2', '\x2', '\x2', 'n', 'l', '\x3', '\x2', '\x2', '\x2', 
		'n', 'o', '\x3', '\x2', '\x2', '\x2', 'o', 'q', '\x3', '\x2', '\x2', '\x2', 
		'p', 'j', '\x3', '\x2', '\x2', '\x2', 'p', 'q', '\x3', '\x2', '\x2', '\x2', 
		'q', ' ', '\x3', '\x2', '\x2', '\x2', 'r', 's', '\a', '?', '\x2', '\x2', 
		's', '\"', '\x3', '\x2', '\x2', '\x2', 't', 'u', '\a', '#', '\x2', '\x2', 
		'u', 'z', '\a', '?', '\x2', '\x2', 'v', 'w', '\a', '>', '\x2', '\x2', 
		'w', 'z', '\a', '@', '\x2', '\x2', 'x', 'z', '\a', '%', '\x2', '\x2', 
		'y', 't', '\x3', '\x2', '\x2', '\x2', 'y', 'v', '\x3', '\x2', '\x2', '\x2', 
		'y', 'x', '\x3', '\x2', '\x2', '\x2', 'z', '$', '\x3', '\x2', '\x2', '\x2', 
		'{', '\x80', '\a', '(', '\x2', '\x2', '|', '}', '\a', '\x43', '\x2', '\x2', 
		'}', '~', '\a', 'P', '\x2', '\x2', '~', '\x80', '\a', '\x46', '\x2', '\x2', 
		'\x7F', '{', '\x3', '\x2', '\x2', '\x2', '\x7F', '|', '\x3', '\x2', '\x2', 
		'\x2', '\x80', '&', '\x3', '\x2', '\x2', '\x2', '\x81', '\x85', '\t', 
		'\x6', '\x2', '\x2', '\x82', '\x83', '\a', 'Q', '\x2', '\x2', '\x83', 
		'\x85', '\a', 'T', '\x2', '\x2', '\x84', '\x81', '\x3', '\x2', '\x2', 
		'\x2', '\x84', '\x82', '\x3', '\x2', '\x2', '\x2', '\x85', '(', '\x3', 
		'\x2', '\x2', '\x2', '\x86', '\x87', '\a', '>', '\x2', '\x2', '\x87', 
		'*', '\x3', '\x2', '\x2', '\x2', '\x88', '\x89', '\a', '@', '\x2', '\x2', 
		'\x89', ',', '\x3', '\x2', '\x2', '\x2', '\x8A', '\x8B', '\x5', ')', '\x15', 
		'\x2', '\x8B', '\x8C', '\x5', '!', '\x11', '\x2', '\x8C', '.', '\x3', 
		'\x2', '\x2', '\x2', '\x8D', '\x8E', '\x5', '+', '\x16', '\x2', '\x8E', 
		'\x8F', '\x5', '!', '\x11', '\x2', '\x8F', '\x30', '\x3', '\x2', '\x2', 
		'\x2', '\x90', '\x92', '\t', '\a', '\x2', '\x2', '\x91', '\x90', '\x3', 
		'\x2', '\x2', '\x2', '\x92', '\x93', '\x3', '\x2', '\x2', '\x2', '\x93', 
		'\x91', '\x3', '\x2', '\x2', '\x2', '\x93', '\x94', '\x3', '\x2', '\x2', 
		'\x2', '\x94', '\x95', '\x3', '\x2', '\x2', '\x2', '\x95', '\x96', '\b', 
		'\x19', '\x2', '\x2', '\x96', '\x32', '\x3', '\x2', '\x2', '\x2', '\x97', 
		'\x9B', '\a', '=', '\x2', '\x2', '\x98', '\x9A', '\n', '\b', '\x2', '\x2', 
		'\x99', '\x98', '\x3', '\x2', '\x2', '\x2', '\x9A', '\x9D', '\x3', '\x2', 
		'\x2', '\x2', '\x9B', '\x99', '\x3', '\x2', '\x2', '\x2', '\x9B', '\x9C', 
		'\x3', '\x2', '\x2', '\x2', '\x9C', '\x9E', '\x3', '\x2', '\x2', '\x2', 
		'\x9D', '\x9B', '\x3', '\x2', '\x2', '\x2', '\x9E', '\x9F', '\b', '\x1A', 
		'\x3', '\x2', '\x9F', '\x34', '\x3', '\x2', '\x2', '\x2', '\xA0', '\xA2', 
		'\a', '\xF', '\x2', '\x2', '\xA1', '\xA0', '\x3', '\x2', '\x2', '\x2', 
		'\xA1', '\xA2', '\x3', '\x2', '\x2', '\x2', '\xA2', '\xA3', '\x3', '\x2', 
		'\x2', '\x2', '\xA3', '\xA6', '\a', '\f', '\x2', '\x2', '\xA4', '\xA6', 
		'\a', '\xF', '\x2', '\x2', '\xA5', '\xA1', '\x3', '\x2', '\x2', '\x2', 
		'\xA5', '\xA4', '\x3', '\x2', '\x2', '\x2', '\xA6', '\xA7', '\x3', '\x2', 
		'\x2', '\x2', '\xA7', '\xA5', '\x3', '\x2', '\x2', '\x2', '\xA7', '\xA8', 
		'\x3', '\x2', '\x2', '\x2', '\xA8', '\xA9', '\x3', '\x2', '\x2', '\x2', 
		'\xA9', '\xAA', '\b', '\x1B', '\x2', '\x2', '\xAA', '\x36', '\x3', '\x2', 
		'\x2', '\x2', '\xAB', '\xB0', '\a', '$', '\x2', '\x2', '\xAC', '\xAF', 
		'\x5', '\x39', '\x1D', '\x2', '\xAD', '\xAF', '\n', '\t', '\x2', '\x2', 
		'\xAE', '\xAC', '\x3', '\x2', '\x2', '\x2', '\xAE', '\xAD', '\x3', '\x2', 
		'\x2', '\x2', '\xAF', '\xB2', '\x3', '\x2', '\x2', '\x2', '\xB0', '\xAE', 
		'\x3', '\x2', '\x2', '\x2', '\xB0', '\xB1', '\x3', '\x2', '\x2', '\x2', 
		'\xB1', '\xB3', '\x3', '\x2', '\x2', '\x2', '\xB2', '\xB0', '\x3', '\x2', 
		'\x2', '\x2', '\xB3', '\xB4', '\a', '$', '\x2', '\x2', '\xB4', '\x38', 
		'\x3', '\x2', '\x2', '\x2', '\xB5', '\xB8', '\a', '^', '\x2', '\x2', '\xB6', 
		'\xB9', '\t', '\n', '\x2', '\x2', '\xB7', '\xB9', '\x5', ';', '\x1E', 
		'\x2', '\xB8', '\xB6', '\x3', '\x2', '\x2', '\x2', '\xB8', '\xB7', '\x3', 
		'\x2', '\x2', '\x2', '\xB9', ':', '\x3', '\x2', '\x2', '\x2', '\xBA', 
		'\xBB', '\a', 'w', '\x2', '\x2', '\xBB', '\xBC', '\x5', '=', '\x1F', '\x2', 
		'\xBC', '\xBD', '\x5', '=', '\x1F', '\x2', '\xBD', '\xBE', '\x5', '=', 
		'\x1F', '\x2', '\xBE', '\xBF', '\x5', '=', '\x1F', '\x2', '\xBF', '<', 
		'\x3', '\x2', '\x2', '\x2', '\xC0', '\xC1', '\t', '\v', '\x2', '\x2', 
		'\xC1', '>', '\x3', '\x2', '\x2', '\x2', '\x13', '\x2', ']', '\x63', 'h', 
		'n', 'p', 'y', '\x7F', '\x84', '\x93', '\x9B', '\xA1', '\xA5', '\xA7', 
		'\xAE', '\xB0', '\xB8', '\x4', '\b', '\x2', '\x2', '\x2', '\x3', '\x2',
	};

	public static readonly ATN _ATN =
		new ATNDeserializer().Deserialize(_serializedATN);


}
} // namespace Roslesinforg.Sigma.SrzParser
