//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.7.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from SRZ.g4 by ANTLR 4.7.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace Roslesinforg.Sigma.SrzParser {
using System;
using System.IO;
using System.Text;
using System.Diagnostics;
using System.Collections.Generic;
using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using DFA = Antlr4.Runtime.Dfa.DFA;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.7.2")]
[System.CLSCompliant(false)]
public partial class SRZParser : Parser {
	protected static DFA[] decisionToDFA;
	protected static PredictionContextCache sharedContextCache = new PredictionContextCache();
	public const int
		DOT=1, COMMA=2, OPENBR=3, CLOSEBR=4, MUL=5, DIV=6, ADD=7, SUB=8, UNDERSCORE=9, 
		ID=10, INT=11, NUMBER=12, EQU=13, NOTEQU=14, AND=15, OR=16, LT=17, GT=18, 
		LE=19, GE=20, WHITESPACE=21, COMMENT=22, NEWLINE=23, STRING=24;
	public const int
		RULE_start = 0, RULE_expression = 1, RULE_params = 2, RULE_function = 3, 
		RULE_variable = 4, RULE_range = 5, RULE_set = 6, RULE_literal = 7;
	public static readonly string[] ruleNames = {
		"start", "expression", "params", "function", "variable", "range", "set", 
		"literal"
	};

	private static readonly string[] _LiteralNames = {
		null, "'.'", "','", "'('", "')'", "'*'", "'/'", "'+'", "'-'", "'_'", null, 
		null, null, "'='", null, null, null, "'<'", "'>'"
	};
	private static readonly string[] _SymbolicNames = {
		null, "DOT", "COMMA", "OPENBR", "CLOSEBR", "MUL", "DIV", "ADD", "SUB", 
		"UNDERSCORE", "ID", "INT", "NUMBER", "EQU", "NOTEQU", "AND", "OR", "LT", 
		"GT", "LE", "GE", "WHITESPACE", "COMMENT", "NEWLINE", "STRING"
	};
	public static readonly IVocabulary DefaultVocabulary = new Vocabulary(_LiteralNames, _SymbolicNames);

	[NotNull]
	public override IVocabulary Vocabulary
	{
		get
		{
			return DefaultVocabulary;
		}
	}

	public override string GrammarFileName { get { return "SRZ.g4"; } }

	public override string[] RuleNames { get { return ruleNames; } }

	public override string SerializedAtn { get { return new string(_serializedATN); } }

	static SRZParser() {
		decisionToDFA = new DFA[_ATN.NumberOfDecisions];
		for (int i = 0; i < _ATN.NumberOfDecisions; i++) {
			decisionToDFA[i] = new DFA(_ATN.GetDecisionState(i), i);
		}
	}

		public SRZParser(ITokenStream input) : this(input, Console.Out, Console.Error) { }

		public SRZParser(ITokenStream input, TextWriter output, TextWriter errorOutput)
		: base(input, output, errorOutput)
	{
		Interpreter = new ParserATNSimulator(this, _ATN, decisionToDFA, sharedContextCache);
	}

	public partial class StartContext : ParserRuleContext {
		public ExpressionContext exp;
		public ITerminalNode Eof() { return GetToken(SRZParser.Eof, 0); }
		public ExpressionContext expression() {
			return GetRuleContext<ExpressionContext>(0);
		}
		public StartContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_start; } }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ISRZVisitor<TResult> typedVisitor = visitor as ISRZVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitStart(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public StartContext start() {
		StartContext _localctx = new StartContext(Context, State);
		EnterRule(_localctx, 0, RULE_start);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 17;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if ((((_la) & ~0x3f) == 0 && ((1L << _la) & ((1L << OPENBR) | (1L << ID) | (1L << INT) | (1L << NUMBER) | (1L << EQU) | (1L << NOTEQU) | (1L << STRING))) != 0)) {
				{
				State = 16; _localctx.exp = expression(0);
				}
			}

			State = 19; Match(Eof);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ExpressionContext : ParserRuleContext {
		public ExpressionContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_expression; } }
	 
		public ExpressionContext() { }
		public virtual void CopyFrom(ExpressionContext context) {
			base.CopyFrom(context);
		}
	}
	public partial class VarExpContext : ExpressionContext {
		public VariableContext variable() {
			return GetRuleContext<VariableContext>(0);
		}
		public VarExpContext(ExpressionContext context) { CopyFrom(context); }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ISRZVisitor<TResult> typedVisitor = visitor as ISRZVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitVarExp(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class LiteralExpContext : ExpressionContext {
		public LiteralContext literal() {
			return GetRuleContext<LiteralContext>(0);
		}
		public LiteralExpContext(ExpressionContext context) { CopyFrom(context); }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ISRZVisitor<TResult> typedVisitor = visitor as ISRZVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitLiteralExp(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class OpExpCompContext : ExpressionContext {
		public ExpressionContext left;
		public IToken op;
		public ExpressionContext right;
		public ExpressionContext[] expression() {
			return GetRuleContexts<ExpressionContext>();
		}
		public ExpressionContext expression(int i) {
			return GetRuleContext<ExpressionContext>(i);
		}
		public ITerminalNode EQU() { return GetToken(SRZParser.EQU, 0); }
		public ITerminalNode NOTEQU() { return GetToken(SRZParser.NOTEQU, 0); }
		public ITerminalNode LT() { return GetToken(SRZParser.LT, 0); }
		public ITerminalNode LE() { return GetToken(SRZParser.LE, 0); }
		public ITerminalNode GT() { return GetToken(SRZParser.GT, 0); }
		public ITerminalNode GE() { return GetToken(SRZParser.GE, 0); }
		public OpExpCompContext(ExpressionContext context) { CopyFrom(context); }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ISRZVisitor<TResult> typedVisitor = visitor as ISRZVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitOpExpComp(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class FuncExpContext : ExpressionContext {
		public FunctionContext function() {
			return GetRuleContext<FunctionContext>(0);
		}
		public FuncExpContext(ExpressionContext context) { CopyFrom(context); }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ISRZVisitor<TResult> typedVisitor = visitor as ISRZVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitFuncExp(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class ParenthesisExpContext : ExpressionContext {
		public ITerminalNode OPENBR() { return GetToken(SRZParser.OPENBR, 0); }
		public ExpressionContext expression() {
			return GetRuleContext<ExpressionContext>(0);
		}
		public ITerminalNode CLOSEBR() { return GetToken(SRZParser.CLOSEBR, 0); }
		public ParenthesisExpContext(ExpressionContext context) { CopyFrom(context); }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ISRZVisitor<TResult> typedVisitor = visitor as ISRZVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitParenthesisExp(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class SetExpContext : ExpressionContext {
		public SetContext set() {
			return GetRuleContext<SetContext>(0);
		}
		public SetExpContext(ExpressionContext context) { CopyFrom(context); }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ISRZVisitor<TResult> typedVisitor = visitor as ISRZVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitSetExp(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class OpExpBoolContext : ExpressionContext {
		public ExpressionContext left;
		public IToken op;
		public ExpressionContext right;
		public ExpressionContext[] expression() {
			return GetRuleContexts<ExpressionContext>();
		}
		public ExpressionContext expression(int i) {
			return GetRuleContext<ExpressionContext>(i);
		}
		public ITerminalNode OR() { return GetToken(SRZParser.OR, 0); }
		public ITerminalNode AND() { return GetToken(SRZParser.AND, 0); }
		public OpExpBoolContext(ExpressionContext context) { CopyFrom(context); }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ISRZVisitor<TResult> typedVisitor = visitor as ISRZVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitOpExpBool(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class OpExpContext : ExpressionContext {
		public ExpressionContext left;
		public IToken op;
		public ExpressionContext right;
		public ExpressionContext[] expression() {
			return GetRuleContexts<ExpressionContext>();
		}
		public ExpressionContext expression(int i) {
			return GetRuleContext<ExpressionContext>(i);
		}
		public ITerminalNode MUL() { return GetToken(SRZParser.MUL, 0); }
		public ITerminalNode DIV() { return GetToken(SRZParser.DIV, 0); }
		public ITerminalNode ADD() { return GetToken(SRZParser.ADD, 0); }
		public ITerminalNode SUB() { return GetToken(SRZParser.SUB, 0); }
		public OpExpContext(ExpressionContext context) { CopyFrom(context); }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ISRZVisitor<TResult> typedVisitor = visitor as ISRZVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitOpExp(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ExpressionContext expression() {
		return expression(0);
	}

	private ExpressionContext expression(int _p) {
		ParserRuleContext _parentctx = Context;
		int _parentState = State;
		ExpressionContext _localctx = new ExpressionContext(Context, _parentState);
		ExpressionContext _prevctx = _localctx;
		int _startState = 2;
		EnterRecursionRule(_localctx, 2, RULE_expression, _p);
		int _la;
		try {
			int _alt;
			EnterOuterAlt(_localctx, 1);
			{
			State = 30;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,1,Context) ) {
			case 1:
				{
				_localctx = new ParenthesisExpContext(_localctx);
				Context = _localctx;
				_prevctx = _localctx;

				State = 22; Match(OPENBR);
				State = 23; expression(0);
				State = 24; Match(CLOSEBR);
				}
				break;
			case 2:
				{
				_localctx = new FuncExpContext(_localctx);
				Context = _localctx;
				_prevctx = _localctx;
				State = 26; function();
				}
				break;
			case 3:
				{
				_localctx = new VarExpContext(_localctx);
				Context = _localctx;
				_prevctx = _localctx;
				State = 27; variable();
				}
				break;
			case 4:
				{
				_localctx = new SetExpContext(_localctx);
				Context = _localctx;
				_prevctx = _localctx;
				State = 28; set();
				}
				break;
			case 5:
				{
				_localctx = new LiteralExpContext(_localctx);
				Context = _localctx;
				_prevctx = _localctx;
				State = 29; literal();
				}
				break;
			}
			Context.Stop = TokenStream.LT(-1);
			State = 49;
			ErrorHandler.Sync(this);
			_alt = Interpreter.AdaptivePredict(TokenStream,3,Context);
			while ( _alt!=2 && _alt!=global::Antlr4.Runtime.Atn.ATN.INVALID_ALT_NUMBER ) {
				if ( _alt==1 ) {
					if ( ParseListeners!=null )
						TriggerExitRuleEvent();
					_prevctx = _localctx;
					{
					State = 47;
					ErrorHandler.Sync(this);
					switch ( Interpreter.AdaptivePredict(TokenStream,2,Context) ) {
					case 1:
						{
						_localctx = new OpExpContext(new ExpressionContext(_parentctx, _parentState));
						((OpExpContext)_localctx).left = _prevctx;
						PushNewRecursionContext(_localctx, _startState, RULE_expression);
						State = 32;
						if (!(Precpred(Context, 9))) throw new FailedPredicateException(this, "Precpred(Context, 9)");
						State = 33;
						((OpExpContext)_localctx).op = TokenStream.LT(1);
						_la = TokenStream.LA(1);
						if ( !(_la==MUL || _la==DIV) ) {
							((OpExpContext)_localctx).op = ErrorHandler.RecoverInline(this);
						}
						else {
							ErrorHandler.ReportMatch(this);
						    Consume();
						}
						State = 34; ((OpExpContext)_localctx).right = expression(10);
						}
						break;
					case 2:
						{
						_localctx = new OpExpContext(new ExpressionContext(_parentctx, _parentState));
						((OpExpContext)_localctx).left = _prevctx;
						PushNewRecursionContext(_localctx, _startState, RULE_expression);
						State = 35;
						if (!(Precpred(Context, 8))) throw new FailedPredicateException(this, "Precpred(Context, 8)");
						State = 36;
						((OpExpContext)_localctx).op = TokenStream.LT(1);
						_la = TokenStream.LA(1);
						if ( !(_la==ADD || _la==SUB) ) {
							((OpExpContext)_localctx).op = ErrorHandler.RecoverInline(this);
						}
						else {
							ErrorHandler.ReportMatch(this);
						    Consume();
						}
						State = 37; ((OpExpContext)_localctx).right = expression(9);
						}
						break;
					case 3:
						{
						_localctx = new OpExpCompContext(new ExpressionContext(_parentctx, _parentState));
						((OpExpCompContext)_localctx).left = _prevctx;
						PushNewRecursionContext(_localctx, _startState, RULE_expression);
						State = 38;
						if (!(Precpred(Context, 7))) throw new FailedPredicateException(this, "Precpred(Context, 7)");
						State = 39;
						((OpExpCompContext)_localctx).op = TokenStream.LT(1);
						_la = TokenStream.LA(1);
						if ( !(_la==EQU || _la==NOTEQU) ) {
							((OpExpCompContext)_localctx).op = ErrorHandler.RecoverInline(this);
						}
						else {
							ErrorHandler.ReportMatch(this);
						    Consume();
						}
						State = 40; ((OpExpCompContext)_localctx).right = expression(8);
						}
						break;
					case 4:
						{
						_localctx = new OpExpCompContext(new ExpressionContext(_parentctx, _parentState));
						((OpExpCompContext)_localctx).left = _prevctx;
						PushNewRecursionContext(_localctx, _startState, RULE_expression);
						State = 41;
						if (!(Precpred(Context, 6))) throw new FailedPredicateException(this, "Precpred(Context, 6)");
						State = 42;
						((OpExpCompContext)_localctx).op = TokenStream.LT(1);
						_la = TokenStream.LA(1);
						if ( !((((_la) & ~0x3f) == 0 && ((1L << _la) & ((1L << LT) | (1L << GT) | (1L << LE) | (1L << GE))) != 0)) ) {
							((OpExpCompContext)_localctx).op = ErrorHandler.RecoverInline(this);
						}
						else {
							ErrorHandler.ReportMatch(this);
						    Consume();
						}
						State = 43; ((OpExpCompContext)_localctx).right = expression(7);
						}
						break;
					case 5:
						{
						_localctx = new OpExpBoolContext(new ExpressionContext(_parentctx, _parentState));
						((OpExpBoolContext)_localctx).left = _prevctx;
						PushNewRecursionContext(_localctx, _startState, RULE_expression);
						State = 44;
						if (!(Precpred(Context, 5))) throw new FailedPredicateException(this, "Precpred(Context, 5)");
						State = 45;
						((OpExpBoolContext)_localctx).op = TokenStream.LT(1);
						_la = TokenStream.LA(1);
						if ( !(_la==AND || _la==OR) ) {
							((OpExpBoolContext)_localctx).op = ErrorHandler.RecoverInline(this);
						}
						else {
							ErrorHandler.ReportMatch(this);
						    Consume();
						}
						State = 46; ((OpExpBoolContext)_localctx).right = expression(6);
						}
						break;
					}
					} 
				}
				State = 51;
				ErrorHandler.Sync(this);
				_alt = Interpreter.AdaptivePredict(TokenStream,3,Context);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			UnrollRecursionContexts(_parentctx);
		}
		return _localctx;
	}

	public partial class ParamsContext : ParserRuleContext {
		public ExpressionContext[] expression() {
			return GetRuleContexts<ExpressionContext>();
		}
		public ExpressionContext expression(int i) {
			return GetRuleContext<ExpressionContext>(i);
		}
		public ITerminalNode[] COMMA() { return GetTokens(SRZParser.COMMA); }
		public ITerminalNode COMMA(int i) {
			return GetToken(SRZParser.COMMA, i);
		}
		public ParamsContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_params; } }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ISRZVisitor<TResult> typedVisitor = visitor as ISRZVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitParams(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ParamsContext @params() {
		ParamsContext _localctx = new ParamsContext(Context, State);
		EnterRule(_localctx, 4, RULE_params);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 52; expression(0);
			State = 57;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while (_la==COMMA) {
				{
				{
				State = 53; Match(COMMA);
				State = 54; expression(0);
				}
				}
				State = 59;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class FunctionContext : ParserRuleContext {
		public ITerminalNode ID() { return GetToken(SRZParser.ID, 0); }
		public ITerminalNode OPENBR() { return GetToken(SRZParser.OPENBR, 0); }
		public ITerminalNode CLOSEBR() { return GetToken(SRZParser.CLOSEBR, 0); }
		public ParamsContext @params() {
			return GetRuleContext<ParamsContext>(0);
		}
		public FunctionContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_function; } }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ISRZVisitor<TResult> typedVisitor = visitor as ISRZVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitFunction(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public FunctionContext function() {
		FunctionContext _localctx = new FunctionContext(Context, State);
		EnterRule(_localctx, 6, RULE_function);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 60; Match(ID);
			State = 61; Match(OPENBR);
			State = 63;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if ((((_la) & ~0x3f) == 0 && ((1L << _la) & ((1L << OPENBR) | (1L << ID) | (1L << INT) | (1L << NUMBER) | (1L << EQU) | (1L << NOTEQU) | (1L << STRING))) != 0)) {
				{
				State = 62; @params();
				}
			}

			State = 65; Match(CLOSEBR);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class VariableContext : ParserRuleContext {
		public ITerminalNode ID() { return GetToken(SRZParser.ID, 0); }
		public VariableContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_variable; } }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ISRZVisitor<TResult> typedVisitor = visitor as ISRZVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitVariable(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public VariableContext variable() {
		VariableContext _localctx = new VariableContext(Context, State);
		EnterRule(_localctx, 8, RULE_variable);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 67; Match(ID);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class RangeContext : ParserRuleContext {
		public ITerminalNode[] INT() { return GetTokens(SRZParser.INT); }
		public ITerminalNode INT(int i) {
			return GetToken(SRZParser.INT, i);
		}
		public ITerminalNode[] COMMA() { return GetTokens(SRZParser.COMMA); }
		public ITerminalNode COMMA(int i) {
			return GetToken(SRZParser.COMMA, i);
		}
		public RangeContext[] range() {
			return GetRuleContexts<RangeContext>();
		}
		public RangeContext range(int i) {
			return GetRuleContext<RangeContext>(i);
		}
		public ITerminalNode[] DOT() { return GetTokens(SRZParser.DOT); }
		public ITerminalNode DOT(int i) {
			return GetToken(SRZParser.DOT, i);
		}
		public RangeContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_range; } }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ISRZVisitor<TResult> typedVisitor = visitor as ISRZVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitRange(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public RangeContext range() {
		RangeContext _localctx = new RangeContext(Context, State);
		EnterRule(_localctx, 10, RULE_range);
		try {
			int _alt;
			EnterOuterAlt(_localctx, 1);
			{
			State = 74;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,6,Context) ) {
			case 1:
				{
				State = 69; Match(INT);
				}
				break;
			case 2:
				{
				{
				State = 70; Match(INT);
				State = 71; Match(DOT);
				State = 72; Match(DOT);
				State = 73; Match(INT);
				}
				}
				break;
			}
			State = 80;
			ErrorHandler.Sync(this);
			_alt = Interpreter.AdaptivePredict(TokenStream,7,Context);
			while ( _alt!=2 && _alt!=global::Antlr4.Runtime.Atn.ATN.INVALID_ALT_NUMBER ) {
				if ( _alt==1 ) {
					{
					{
					State = 76; Match(COMMA);
					State = 77; range();
					}
					} 
				}
				State = 82;
				ErrorHandler.Sync(this);
				_alt = Interpreter.AdaptivePredict(TokenStream,7,Context);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class SetContext : ParserRuleContext {
		public RangeContext range() {
			return GetRuleContext<RangeContext>(0);
		}
		public ITerminalNode EQU() { return GetToken(SRZParser.EQU, 0); }
		public ITerminalNode NOTEQU() { return GetToken(SRZParser.NOTEQU, 0); }
		public SetContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_set; } }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ISRZVisitor<TResult> typedVisitor = visitor as ISRZVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitSet(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public SetContext set() {
		SetContext _localctx = new SetContext(Context, State);
		EnterRule(_localctx, 12, RULE_set);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 83;
			_la = TokenStream.LA(1);
			if ( !(_la==EQU || _la==NOTEQU) ) {
			ErrorHandler.RecoverInline(this);
			}
			else {
				ErrorHandler.ReportMatch(this);
			    Consume();
			}
			State = 84; range();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class LiteralContext : ParserRuleContext {
		public IToken typ;
		public ITerminalNode INT() { return GetToken(SRZParser.INT, 0); }
		public ITerminalNode NUMBER() { return GetToken(SRZParser.NUMBER, 0); }
		public ITerminalNode STRING() { return GetToken(SRZParser.STRING, 0); }
		public LiteralContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_literal; } }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ISRZVisitor<TResult> typedVisitor = visitor as ISRZVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitLiteral(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public LiteralContext literal() {
		LiteralContext _localctx = new LiteralContext(Context, State);
		EnterRule(_localctx, 14, RULE_literal);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 86;
			_localctx.typ = TokenStream.LT(1);
			_la = TokenStream.LA(1);
			if ( !((((_la) & ~0x3f) == 0 && ((1L << _la) & ((1L << INT) | (1L << NUMBER) | (1L << STRING))) != 0)) ) {
				_localctx.typ = ErrorHandler.RecoverInline(this);
			}
			else {
				ErrorHandler.ReportMatch(this);
			    Consume();
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public override bool Sempred(RuleContext _localctx, int ruleIndex, int predIndex) {
		switch (ruleIndex) {
		case 1: return expression_sempred((ExpressionContext)_localctx, predIndex);
		}
		return true;
	}
	private bool expression_sempred(ExpressionContext _localctx, int predIndex) {
		switch (predIndex) {
		case 0: return Precpred(Context, 9);
		case 1: return Precpred(Context, 8);
		case 2: return Precpred(Context, 7);
		case 3: return Precpred(Context, 6);
		case 4: return Precpred(Context, 5);
		}
		return true;
	}

	private static char[] _serializedATN = {
		'\x3', '\x608B', '\xA72A', '\x8133', '\xB9ED', '\x417C', '\x3BE7', '\x7786', 
		'\x5964', '\x3', '\x1A', '[', '\x4', '\x2', '\t', '\x2', '\x4', '\x3', 
		'\t', '\x3', '\x4', '\x4', '\t', '\x4', '\x4', '\x5', '\t', '\x5', '\x4', 
		'\x6', '\t', '\x6', '\x4', '\a', '\t', '\a', '\x4', '\b', '\t', '\b', 
		'\x4', '\t', '\t', '\t', '\x3', '\x2', '\x5', '\x2', '\x14', '\n', '\x2', 
		'\x3', '\x2', '\x3', '\x2', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', 
		'\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', 
		'\x3', '\x3', '\x5', '\x3', '!', '\n', '\x3', '\x3', '\x3', '\x3', '\x3', 
		'\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', 
		'\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', 
		'\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\a', '\x3', '\x32', '\n', '\x3', 
		'\f', '\x3', '\xE', '\x3', '\x35', '\v', '\x3', '\x3', '\x4', '\x3', '\x4', 
		'\x3', '\x4', '\a', '\x4', ':', '\n', '\x4', '\f', '\x4', '\xE', '\x4', 
		'=', '\v', '\x4', '\x3', '\x5', '\x3', '\x5', '\x3', '\x5', '\x5', '\x5', 
		'\x42', '\n', '\x5', '\x3', '\x5', '\x3', '\x5', '\x3', '\x6', '\x3', 
		'\x6', '\x3', '\a', '\x3', '\a', '\x3', '\a', '\x3', '\a', '\x3', '\a', 
		'\x5', '\a', 'M', '\n', '\a', '\x3', '\a', '\x3', '\a', '\a', '\a', 'Q', 
		'\n', '\a', '\f', '\a', '\xE', '\a', 'T', '\v', '\a', '\x3', '\b', '\x3', 
		'\b', '\x3', '\b', '\x3', '\t', '\x3', '\t', '\x3', '\t', '\x2', '\x3', 
		'\x4', '\n', '\x2', '\x4', '\x6', '\b', '\n', '\f', '\xE', '\x10', '\x2', 
		'\b', '\x3', '\x2', '\a', '\b', '\x3', '\x2', '\t', '\n', '\x3', '\x2', 
		'\xF', '\x10', '\x3', '\x2', '\x13', '\x16', '\x3', '\x2', '\x11', '\x12', 
		'\x4', '\x2', '\r', '\xE', '\x1A', '\x1A', '\x2', '`', '\x2', '\x13', 
		'\x3', '\x2', '\x2', '\x2', '\x4', ' ', '\x3', '\x2', '\x2', '\x2', '\x6', 
		'\x36', '\x3', '\x2', '\x2', '\x2', '\b', '>', '\x3', '\x2', '\x2', '\x2', 
		'\n', '\x45', '\x3', '\x2', '\x2', '\x2', '\f', 'L', '\x3', '\x2', '\x2', 
		'\x2', '\xE', 'U', '\x3', '\x2', '\x2', '\x2', '\x10', 'X', '\x3', '\x2', 
		'\x2', '\x2', '\x12', '\x14', '\x5', '\x4', '\x3', '\x2', '\x13', '\x12', 
		'\x3', '\x2', '\x2', '\x2', '\x13', '\x14', '\x3', '\x2', '\x2', '\x2', 
		'\x14', '\x15', '\x3', '\x2', '\x2', '\x2', '\x15', '\x16', '\a', '\x2', 
		'\x2', '\x3', '\x16', '\x3', '\x3', '\x2', '\x2', '\x2', '\x17', '\x18', 
		'\b', '\x3', '\x1', '\x2', '\x18', '\x19', '\a', '\x5', '\x2', '\x2', 
		'\x19', '\x1A', '\x5', '\x4', '\x3', '\x2', '\x1A', '\x1B', '\a', '\x6', 
		'\x2', '\x2', '\x1B', '!', '\x3', '\x2', '\x2', '\x2', '\x1C', '!', '\x5', 
		'\b', '\x5', '\x2', '\x1D', '!', '\x5', '\n', '\x6', '\x2', '\x1E', '!', 
		'\x5', '\xE', '\b', '\x2', '\x1F', '!', '\x5', '\x10', '\t', '\x2', ' ', 
		'\x17', '\x3', '\x2', '\x2', '\x2', ' ', '\x1C', '\x3', '\x2', '\x2', 
		'\x2', ' ', '\x1D', '\x3', '\x2', '\x2', '\x2', ' ', '\x1E', '\x3', '\x2', 
		'\x2', '\x2', ' ', '\x1F', '\x3', '\x2', '\x2', '\x2', '!', '\x33', '\x3', 
		'\x2', '\x2', '\x2', '\"', '#', '\f', '\v', '\x2', '\x2', '#', '$', '\t', 
		'\x2', '\x2', '\x2', '$', '\x32', '\x5', '\x4', '\x3', '\f', '%', '&', 
		'\f', '\n', '\x2', '\x2', '&', '\'', '\t', '\x3', '\x2', '\x2', '\'', 
		'\x32', '\x5', '\x4', '\x3', '\v', '(', ')', '\f', '\t', '\x2', '\x2', 
		')', '*', '\t', '\x4', '\x2', '\x2', '*', '\x32', '\x5', '\x4', '\x3', 
		'\n', '+', ',', '\f', '\b', '\x2', '\x2', ',', '-', '\t', '\x5', '\x2', 
		'\x2', '-', '\x32', '\x5', '\x4', '\x3', '\t', '.', '/', '\f', '\a', '\x2', 
		'\x2', '/', '\x30', '\t', '\x6', '\x2', '\x2', '\x30', '\x32', '\x5', 
		'\x4', '\x3', '\b', '\x31', '\"', '\x3', '\x2', '\x2', '\x2', '\x31', 
		'%', '\x3', '\x2', '\x2', '\x2', '\x31', '(', '\x3', '\x2', '\x2', '\x2', 
		'\x31', '+', '\x3', '\x2', '\x2', '\x2', '\x31', '.', '\x3', '\x2', '\x2', 
		'\x2', '\x32', '\x35', '\x3', '\x2', '\x2', '\x2', '\x33', '\x31', '\x3', 
		'\x2', '\x2', '\x2', '\x33', '\x34', '\x3', '\x2', '\x2', '\x2', '\x34', 
		'\x5', '\x3', '\x2', '\x2', '\x2', '\x35', '\x33', '\x3', '\x2', '\x2', 
		'\x2', '\x36', ';', '\x5', '\x4', '\x3', '\x2', '\x37', '\x38', '\a', 
		'\x4', '\x2', '\x2', '\x38', ':', '\x5', '\x4', '\x3', '\x2', '\x39', 
		'\x37', '\x3', '\x2', '\x2', '\x2', ':', '=', '\x3', '\x2', '\x2', '\x2', 
		';', '\x39', '\x3', '\x2', '\x2', '\x2', ';', '<', '\x3', '\x2', '\x2', 
		'\x2', '<', '\a', '\x3', '\x2', '\x2', '\x2', '=', ';', '\x3', '\x2', 
		'\x2', '\x2', '>', '?', '\a', '\f', '\x2', '\x2', '?', '\x41', '\a', '\x5', 
		'\x2', '\x2', '@', '\x42', '\x5', '\x6', '\x4', '\x2', '\x41', '@', '\x3', 
		'\x2', '\x2', '\x2', '\x41', '\x42', '\x3', '\x2', '\x2', '\x2', '\x42', 
		'\x43', '\x3', '\x2', '\x2', '\x2', '\x43', '\x44', '\a', '\x6', '\x2', 
		'\x2', '\x44', '\t', '\x3', '\x2', '\x2', '\x2', '\x45', '\x46', '\a', 
		'\f', '\x2', '\x2', '\x46', '\v', '\x3', '\x2', '\x2', '\x2', 'G', 'M', 
		'\a', '\r', '\x2', '\x2', 'H', 'I', '\a', '\r', '\x2', '\x2', 'I', 'J', 
		'\a', '\x3', '\x2', '\x2', 'J', 'K', '\a', '\x3', '\x2', '\x2', 'K', 'M', 
		'\a', '\r', '\x2', '\x2', 'L', 'G', '\x3', '\x2', '\x2', '\x2', 'L', 'H', 
		'\x3', '\x2', '\x2', '\x2', 'M', 'R', '\x3', '\x2', '\x2', '\x2', 'N', 
		'O', '\a', '\x4', '\x2', '\x2', 'O', 'Q', '\x5', '\f', '\a', '\x2', 'P', 
		'N', '\x3', '\x2', '\x2', '\x2', 'Q', 'T', '\x3', '\x2', '\x2', '\x2', 
		'R', 'P', '\x3', '\x2', '\x2', '\x2', 'R', 'S', '\x3', '\x2', '\x2', '\x2', 
		'S', '\r', '\x3', '\x2', '\x2', '\x2', 'T', 'R', '\x3', '\x2', '\x2', 
		'\x2', 'U', 'V', '\t', '\x4', '\x2', '\x2', 'V', 'W', '\x5', '\f', '\a', 
		'\x2', 'W', '\xF', '\x3', '\x2', '\x2', '\x2', 'X', 'Y', '\t', '\a', '\x2', 
		'\x2', 'Y', '\x11', '\x3', '\x2', '\x2', '\x2', '\n', '\x13', ' ', '\x31', 
		'\x33', ';', '\x41', 'L', 'R',
	};

	public static readonly ATN _ATN =
		new ATNDeserializer().Deserialize(_serializedATN);


}
} // namespace Roslesinforg.Sigma.SrzParser
